/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef data_holder_CONSTANTS_H
#define data_holder_CONSTANTS_H

#include "data_holder_types.h"



class data_holderConstants {
 public:
  data_holderConstants();

};

extern const data_holderConstants g_data_holder_constants;



#endif
