/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "data_holder_constants.h"



const data_holderConstants g_data_holder_constants;

data_holderConstants::data_holderConstants() {
}



