/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef leader_election_CONSTANTS_H
#define leader_election_CONSTANTS_H

#include "leader_election_types.h"



class leader_electionConstants {
 public:
  leader_electionConstants();

};

extern const leader_electionConstants g_leader_election_constants;



#endif
