/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "leader_election_constants.h"



const leader_electionConstants g_leader_election_constants;

leader_electionConstants::leader_electionConstants() {
}



